(defproject nebulosity "0.1.0-SNAPSHOT"
  :description "Clojure code surrounded by nebulosity, eventually to reach star state"
  :url "https://github.com/claj/nebulosity"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [enlive "1.1.5"]
                 [bytebuffer "0.2.0"]
                 [nio "1.0.2"]
                 [cc.artifice/clj-ml "0.5.0-SNAPSHOT"]
                 [gloss "0.2.2"]
                 [reduce-fsm "0.1.0"]
                 [zookeeper-clj "0.9.1"]
                 [clj-net-pcap "1.6.0"]
                 [com.cemerick/pomegranate "0.2.0"]
                 [org.clojure/core.logic "0.8.5"]
                 [org.clojure/core.match "0.2.0"]
                 [org.clojure/math.numeric-tower "0.0.3"]
                 [org.clojure/core.contracts "0.0.5"]
                 [org.clojure/data.priority-map "0.0.4"]
                 [org.clojure/test.generative "0.5.0"]
                 [org.clojure/data.xml "0.0.7"]
                 [org.clojure/data.zip "0.1.1"]
                 [org.clojure/data.generators "0.1.2"]
                 [org.clojure/core.cache "0.6.3"]
                 [org.clojure/core.unify "0.5.5"]
                 [org.clojure/core.memoize "0.5.6"]
                 [org.clojure/tools.logging "0.2.6"]
                 [org.clojure/tools.trace "0.7.6"]
                 [org.clojure/data.json "0.2.3"]
                 [org.clojure/data.csv "0.1.2"]
                 [org.clojure/java.jmx "0.2.0"]
                 [org.clojure/java.data "0.1.1"]
                 [org.clojure/tools.macro "0.1.2"]
                 [org.clojure/data.fressian "0.2.0"]
                 [org.clojure/data.finger-tree "0.0.1"]
                 [org.clojure/core.async "0.1.267.0-0d7780-alpha"]
                 [criterium "0.4.2"]])
